Repository commercetools/connect-payment-integration-paypal, pull requests merged in 2024-06, with the labels that each got.

#125 chore(connector): improve dev tools for ease of testing
  README.md
  docker-compose.yaml
  enabler/index.html
  enabler/package-lock.json
  package-lock.json
  processor/docker-compose.yaml
  processor/package-lock.json
  processor/package.json
Labels: 5 min review

#131 chore(connector): Inform users on scopes and correct urls
  connect.yaml
Labels: missing-jira, 1 min review

#128 ci(latest): autoupdate checkout connector
  .github/workflows/ci.yml
  .github/workflows/latest.yml
  .github/workflows/publish.yml
Labels: 5 min review, missing-jira

#133 ci(publish): fix publish repo
  .github/workflows/publish.yml
Labels: missing-jira

#137 chore(all): release v1.0.9
  enabler/package.json
  processor/package.json
Labels: missing-jira

#140 style(code-scanning): removed unnecessary "await"
  processor/src/services/paypal-payment.service.ts
Labels: missing-jira
